wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1679028534.870412
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.13.11
      8:
      - 5
dataset:
  desc: null
  value: OpenAI Gym
epochs:
  desc: null
  value: 1
goal_reward:
  desc: null
  value: 10
